MTSDK-235 HLD SCP
MyPureCloud/genesys-messenger-transport-mobile-sdk pull request #214
Opened 2023-09-18 20:31 UTC by AfanasievAnton

- Add diagram with detailed attachment flow.

2023-09-20 11:09 UTC, KalmanPerkelGenesys requested changes

2023-09-20 11:09 UTC, KalmanPerkelGenesys commented on transport/uml/scp/scp_hld.puml
> +MessageStore -> App : messageListener(MessageEvent(AttachmentUpdated(attachmentId, State.Uploading))
Since `MessageStore` is an internal class, can we report the status to `MessagingClient`, which can then pass it to the app?

2023-09-20 15:01 UTC, AfanasievAnton commented on transport/uml/scp/scp_hld.puml
> +AttachmentHandler -> MessageStore : updateAttachmentStateWith(attachmentId, State.Presigning)
As discussed tech-debt ticket was created to make this improvement:
https://inindca.atlassian.net/browse/MTSDK-252

2023-09-20 15:03 UTC, AfanasievAnton commented on transport/uml/scp/scp_hld.puml
> +MessagingClient -> MessagingClient : generateAttachmentId
This step in diagram might be misleading. 
There is no dedicated method in MessagingClient to generate attachmentId, it is injected into attachmentHandler.prepare() function for testability.

2023-09-21 10:56 UTC, KalmanPerkelGenesys approved these changes

2023-09-21 14:22 UTC, merged